# Generated by Django 5.2.8 on 2025-11-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_customer_id_alter_payment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
