# Generated by Django 5.2.8 on 2025-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Número da parcela')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor principal')),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comissão')),
                ('late_fee_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Juros por atraso')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor total')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
