# Generated by Django 5.2.8 on 2025-11-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installments', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='sales.sale'),
        ),
    ]
