# Generated by Django 5.2.8 on 2025-11-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_initial'),
        ('sales', '0002_alter_sale_options_alter_sale_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='Data do vencimento'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='sales.sale', verbose_name='Título da venda'),
        ),
    ]
