# Generated by Django 5.2.8 on 2025-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_alter_installment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
