# Generated by Django 5.2.8 on 2025-11-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installments', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor aplicado')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_allocations', to='installments.installment')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_allocations', to='payments.payment')),
            ],
        ),
    ]
