# Generated by Django 5.2.8 on 2025-11-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_alter_installment_description_and_more'),
        ('payments', '0002_alter_payment_customer_id_alter_payment_description_and_more'),
        ('payments_allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_allocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='payment_allocation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='payment_allocation',
            name='installment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_allocations', to='installments.installment', verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='payment_allocation',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_allocations', to='payments.payment', verbose_name='Pagamento'),
        ),
    ]
