# Generated by Django 5.2.8 on 2025-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_allocations', '0002_alter_payment_allocation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_allocation',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
