# Generated by Django 5.2.8 on 2025-11-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_allocations', '0003_rename_payment_id_payment_allocation_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_allocation',
            old_name='installment_id',
            new_name='installment',
        ),
    ]
