# Generated by Django 5.2.8 on 2025-11-06 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('categories', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sale_date', models.DateField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('installment_quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='O número de parcelas deve ser igual ou maior que 1.'), django.core.validators.MaxValueValidator(12, message='O número máximo de parcelas é 12.')], verbose_name='Quantidade de parcelas')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cards.card')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='categories.category')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
