# Generated by Django 5.2.8 on 2025-11-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_description_alter_card_payment_due_day_and_more'),
        ('categories', '0002_alter_category_description_alter_category_title'),
        ('customers', '0002_alter_customer_address_alter_customer_description_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.AlterField(
            model_name='sale',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cards.card', verbose_name='Cartão'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de custo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='Data da venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
