# Generated by Django 5.2.8 on 2025-11-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_alter_sale_card_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
