# Generated by Django 5.2.8 on 2025-11-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_customer_id_sale_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='category_id',
            new_name='category',
        ),
    ]
