# Generated by Django 5.2.8 on 2025-11-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_category_id_sale_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='card_id',
            new_name='card',
        ),
    ]
